version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple and stylecheck)
    - unused        # Check for unused code
    
    # Additional quality linters
    - misspell      # Find commonly misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - bodyclose     # Check HTTP response body is closed
    - noctx         # Find sending http request without context.Context
    - gosec         # Security-focused linter
    - gocritic      # Most opinionated linter
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - prealloc      # Find slice declarations that could potentially be preallocated
    - copyloopvar   # Checks for pointers to enclosing loop variables (replaces exportloopref)
    - nilerr        # Finds code that returns nil even if it checks that error is not nil
    - errorlint     # Find code that will cause problems with error wrapping
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - nolintlint    # Reports ill-formed or insufficient nolint directives

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for most projects
    
    gosec:
      excludes:
        - G404  # Use of weak random number generator - OK for non-crypto use
    
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      disabled-checks:
        - unnamedResult
        - whyNoLint
    
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
          disabled: true

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gosec
          - gocritic
          - noctx
          - bodyclose
      
      # Exclude specific issues
      - text: "G304: Potential file inclusion via variable"
        linters:
          - gosec
      
      # Ignore long lines in generated files
      - path: webfs_embed\.go
        linters:
          - lll
