services:

  flightlesssomething:
    image: ghcr.io/erkexzcx/flightlesssomething:latest
    container_name: flightlesssomething
    ports:
      - "8080:8080"
    volumes:
      - ./flightlesssomething/data:/data
    environment:
      - FS_BIND="0.0.0.0:8080"
      - FS_DATA_DIR="/data"
      - FS_DISCORD_CLIENT_ID="xxxxxxxxxxxxxxxxxx"
      - FS_DISCORD_CLIENT_SECRET="xxxxxxxxxxxxxxxxxx"
      - FS_DISCORD_REDIRECT_URL="<scheme>://<domain>/login/callback"
    restart: unless-stopped
